In [74]:
import pandas as pd
import numpy as np

In [34]:
data = pd.read_csv('Amazon_-_Movies_and_TV_Ratings.csv')

In [35]:
data.head()

,user_id,Movie1,Movie2,Movie3,Movie4,Movie5,Movie6,Movie7,Movie8,Movie9,...,Movie197,Movie198,Movie199,Movie200,Movie201,Movie202,Movie203,Movie204,Movie205,Movie206
0,A3R5OBKS7OM2IR,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AH3QC2PC1VTGP,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A3LKP6WPMP9UKX,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AVIY68KEPQ5ZD,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A1CV1WROP5KTTW,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
data.describe().transpose()

          count      mean       std  min   25%  50%  75%  max
Movie1      1.0  5.000000       NaN  5.0  5.00  5.0  5.0  5.0
Movie2      1.0  5.000000       NaN  5.0  5.00  5.0  5.0  5.0
Movie3      1.0  2.000000       NaN  2.0  2.00  2.0  2.0  2.0
Movie4      2.0  5.000000  0.000000  5.0  5.00  5.0  5.0  5.0
Movie5     29.0  4.103448  1.496301  1.0  4.00  5.0  5.0  5.0
...         ...       ...       ...  ...   ...  ...  ...  ...
Movie202    6.0  4.333333  1.632993  1.0  5.00  5.0  5.0  5.0
Movie203    1.0  3.000000       NaN  3.0  3.00  3.0  3.0  3.0
Movie204    8.0  4.375000  1.407886  1.0  4.75  5.0  5.0  5.0
Movie205   35.0  4.628571  0.910259  1.0  5.00  5.0  5.0  5.0
Movie206   13.0  4.923077  0.277350  4.0  5.00  5.0  5.0  5.0

[206 rows x 8 columns]

In [37]:
data.isna().sum()

user_id        0
Movie1      4847
Movie2      4847
Movie3      4847
Movie4      4846
            ...
Movie202    4842
Movie203    4847
Movie204    4840
Movie205    4813
Movie206    4835
Length: 207, dtype: int64

In [38]:
data.count()

user_id     4848
Movie1         1
Movie2         1
Movie3         1
Movie4         2
            ...
Movie202       6
Movie203       1
Movie204       8
Movie205      35
Movie206      13
Length: 207, dtype: int64

In [25]:
data = data.dropna(how='all')

In [64]:
views_dict = dict(data.count()[1:])

In [65]:
for movie,views in views_dict.items():
    if views == max(views_dict.values()):
        print(f'{movie} has maximum views/ratings')

Movie127 has maximum views/ratings

In [69]:
total_rating = []
for col in data.columns:
    if col != 'user_id':
        total_rating.append(data[col].sum())

In [71]:
view_count = list(data.count()[1:])

In [77]:
task_2 = list(np.array(total_rating)/np.array(view_count))

In [91]:
avg_rating = {}
for i in range(len(list(data.count()[1:].index))):
    avg_rating[list(data.count()[1:].index)[i]] = task_2[i]

In [92]:
avg_rating

{'Movie1': 5.0,
 'Movie2': 5.0,
 'Movie3': 2.0,
 'Movie4': 5.0,
 'Movie5': 4.103448275862069,
 'Movie6': 4.0,
 'Movie7': 5.0,
 'Movie8': 5.0,
 'Movie9': 5.0,
 'Movie10': 5.0,
 'Movie11': 5.0,
 'Movie12': 5.0,
 'Movie13': 5.0,
 'Movie14': 4.0,
 'Movie15': 5.0,
 'Movie16': 4.51875,
 'Movie17': 3.0,
 'Movie18': 5.0,
 'Movie19': 3.5,
 'Movie20': 3.0,
 'Movie21': 5.0,
 'Movie22': 5.0,
 'Movie23': 5.0,
 'Movie24': 4.4,
 'Movie25': 5.0,
 'Movie26': 3.0,
 'Movie27': 5.0,
 'Movie28': 3.3333333333333335,
 'Movie29': 4.806584362139918,
 'Movie30': 4.5,
 'Movie31': 5.0,
 'Movie32': 4.5,
 'Movie33': 5.0,
 'Movie34': 5.0,
 'Movie35': 5.0,
 'Movie36': 5.0,
 'Movie37': 5.0,
 'Movie38': 5.0,
 'Movie39': 5.0,
 'Movie40': 5.0,
 'Movie41': 5.0,
 'Movie42': 5.0,
 'Movie43': 4.857142857142857,
 'Movie44': 5.0,
 'Movie45': 1.0,
 'Movie46': 5.0,
 'Movie47': 5.0,
 'Movie48': 5.0,
 'Movie49': 5.0,
 'Movie50': 5.0,
 'Movie51': 4.5,
 'Movie52': 3.4705882352941178,
 'Movie53': 2.0,
 'Movie54': 5.0,
 'Movie55': 5.0,
 'Movie56': 5.0,
 'Movie57': 5.0,
 'Movie58': 1.0,
 'Movie59': 2.0,
 'Movie60': 1.0,
 'Movie61': 5.0,
 'Movie62': 3.0,
 'Movie63': 5.0,
 'Movie64': 3.0,
 'Movie65': 5.0,
 'Movie66': 5.0,
 'Movie67': 1.0,
 'Movie68': 5.0,
 'Movie69': 1.0,
 'Movie70': 5.0,
 'Movie71': 4.0,
 'Movie72': 5.0,
 'Movie73': 2.0,
 'Movie74': 5.0,
 'Movie75': 5.0,
 'Movie76': 5.0,
 'Movie77': 5.0,
 'Movie78': 5.0,
 'Movie79': 5.0,
 'Movie80': 4.0,
 'Movie81': 4.416666666666667,
 'Movie82': 5.0,
 'Movie83': 3.0,
 'Movie84': 5.0,
 'Movie85': 5.0,
 'Movie86': 4.666666666666667,
 'Movie87': 5.0,
 'Movie88': 4.0,
 'Movie89': 4.578313253012048,
 'Movie90': 1.8333333333333333,
 'Movie91': 4.578125,
 'Movie92': 4.772277227722772,
 'Movie93': 5.0,
 'Movie94': 4.333333333333333,
 'Movie95': 3.3333333333333335,
 'Movie96': 5.0,
 'Movie97': 4.8,
 'Movie98': 5.0,
 'Movie99': 4.0,
 'Movie100': 4.0,
 'Movie101': 5.0,
 'Movie102': 4.0,
 'Movie103': 4.5625,
 'Movie104': 4.5,
 'Movie105': 5.0,
 'Movie106': 5.0,
 'Movie107': 4.0,
 'Movie108': 4.666666666666667,
 'Movie109': 4.384615384615385,
 'Movie110': 4.875,
 'Movie111': 4.641025641025641,
 'Movie112': 5.0,
 'Movie113': 3.75,
 'Movie114': 4.428571428571429,
 'Movie115': 4.0,
 'Movie116': 5.0,
 'Movie117': 4.7272727272727275,
 'Movie118': 5.0,
 'Movie119': 4.375,
 'Movie120': 5.0,
 'Movie121': 4.25,
 'Movie122': 5.0,
 'Movie123': 5.0,
 'Movie124': 4.75,
 'Movie125': 4.8,
 'Movie126': 4.5,
 'Movie127': 4.11197578901859,
 'Movie128': 5.0,
 'Movie129': 4.0,
 'Movie130': 4.5,
 'Movie131': 5.0,
 'Movie132': 5.0,
 'Movie133': 5.0,
 'Movie134': 4.0,
 'Movie135': 5.0,
 'Movie136': 5.0,
 'Movie137': 4.0,
 'Movie138': 4.076923076923077,
 'Movie139': 5.0,
 'Movie140': 4.833910034602076,
 'Movie141': 4.142857142857143,
 'Movie142': 5.0,
 'Movie143': 5.0,
 'Movie144': 1.0,
 'Movie145': 5.0,
 'Movie146': 4.0,
 'Movie147': 5.0,
 'Movie148': 5.0,
 'Movie149': 5.0,
 'Movie150': 5.0,
 'Movie151': 4.5,
 'Movie152': 5.0,
 'Movie153': 5.0,
 'Movie154': 1.0,
 'Movie155': 4.0,
 'Movie156': 4.0,
 'Movie157': 5.0,
 'Movie158': 4.818181818181818,
 'Movie159': 3.0,
 'Movie160': 4.666666666666667,
 'Movie161': 4.6,
 'Movie162': 4.866666666666666,
 'Movie163': 4.461538461538462,
 'Movie164': 5.0,
 'Movie165': 5.0,
 'Movie166': 4.0,
 'Movie167': 5.0,
 'Movie168': 5.0,
 'Movie169': 5.0,
 'Movie170': 4.333333333333333,
 'Movie171': 2.0,
 'Movie172': 4.5,
 'Movie173': 4.733333333333333,
 'Movie174': 4.75,
 'Movie175': 5.0,
 'Movie176': 5.0,
 'Movie177': 5.0,
 'Movie178': 5.0,
 'Movie179': 4.714285714285714,
 'Movie180': 5.0,
 'Movie181': 5.0,
 'Movie182': 4.733333333333333,
 'Movie183': 5.0,
 'Movie184': 4.823529411764706,
 'Movie185': 4.791666666666667,
 'Movie186': 5.0,
 'Movie187': 5.0,
 'Movie188': 5.0,
 'Movie189': 5.0,
 'Movie190': 4.714285714285714,
 'Movie191': 5.0,
 'Movie192': 4.5,
 'Movie193': 4.571428571428571,
 'Movie194': 4.714285714285714,
 'Movie195': 4.0,
 'Movie196': 4.888888888888889,
 'Movie197': 3.8,
 'Movie198': 5.0,
 'Movie199': 5.0,
 'Movie200': 4.625,
 'Movie201': 4.333333333333333,
 'Movie202': 4.333333333333333,
 'Movie203': 3.0,
 'Movie204': 4.375,
 'Movie205': 4.628571428571429,
 'Movie206': 4.923076923076923}

In [94]:
views_dict

{'Movie1': 1,
 'Movie2': 1,
 'Movie3': 1,
 'Movie4': 2,
 'Movie5': 29,
 'Movie6': 1,
 'Movie7': 1,
 'Movie8': 1,
 'Movie9': 1,
 'Movie10': 1,
 'Movie11': 2,
 'Movie12': 5,
 'Movie13': 1,
 'Movie14': 1,
 'Movie15': 1,
 'Movie16': 320,
 'Movie17': 1,
 'Movie18': 1,
 'Movie19': 2,
 'Movie20': 1,
 'Movie21': 1,
 'Movie22': 2,
 'Movie23': 3,
 'Movie24': 5,
 'Movie25': 1,
 'Movie26': 3,
 'Movie27': 1,
 'Movie28': 3,
 'Movie29': 243,
 'Movie30': 2,
 'Movie31': 2,
 'Movie32': 2,
 'Movie33': 1,
 'Movie34': 1,
 'Movie35': 1,
 'Movie36': 1,
 'Movie37': 1,
 'Movie38': 1,
 'Movie39': 4,
 'Movie40': 3,
 'Movie41': 1,
 'Movie42': 1,
 'Movie43': 7,
 'Movie44': 2,
 'Movie45': 1,
 'Movie46': 1,
 'Movie47': 1,
 'Movie48': 1,
 'Movie49': 1,
 'Movie50': 1,
 'Movie51': 2,
 'Movie52': 17,
 'Movie53': 3,
 'Movie54': 1,
 'Movie55': 1,
 'Movie56': 1,
 'Movie57': 1,
 'Movie58': 1,
 'Movie59': 1,
 'Movie60': 1,
 'Movie61': 1,
 'Movie62': 4,
 'Movie63': 1,
 'Movie64': 1,
 'Movie65': 1,
 'Movie66': 1,
 'Movie67': 1,
 'Movie68': 1,
 'Movie69': 1,
 'Movie70': 2,
 'Movie71': 1,
 'Movie72': 1,
 'Movie73': 1,
 'Movie74': 1,
 'Movie75': 1,
 'Movie76': 2,
 'Movie77': 1,
 'Movie78': 1,
 'Movie79': 2,
 'Movie80': 1,
 'Movie81': 12,
 'Movie82': 2,
 'Movie83': 1,
 'Movie84': 1,
 'Movie85': 3,
 'Movie86': 21,
 'Movie87': 1,
 'Movie88': 1,
 'Movie89': 83,
 'Movie90': 18,
 'Movie91': 128,
 'Movie92': 101,
 'Movie93': 2,
 'Movie94': 3,
 'Movie95': 6,
 'Movie96': 3,
 'Movie97': 5,
 'Movie98': 1,
 'Movie99': 2,
 'Movie100': 1,
 'Movie101': 5,
 'Movie102': 2,
 'Movie103': 272,
 'Movie104': 4,
 'Movie105': 3,
 'Movie106': 1,
 'Movie107': 39,
 'Movie108': 54,
 'Movie109': 13,
 'Movie110': 8,
 'Movie111': 39,
 'Movie112': 2,
 'Movie113': 4,
 'Movie114': 7,
 'Movie115': 1,
 'Movie116': 1,
 'Movie117': 11,
 'Movie118': 5,
 'Movie119': 8,
 'Movie120': 3,
 'Movie121': 4,
 'Movie122': 4,
 'Movie123': 1,
 'Movie124': 4,
 'Movie125': 5,
 'Movie126': 2,
 'Movie127': 2313,
 'Movie128': 3,
 'Movie129': 3,
 'Movie130': 4,
 'Movie131': 4,
 'Movie132': 3,
 'Movie133': 1,
 'Movie134': 6,
 'Movie135': 1,
 'Movie136': 2,
 'Movie137': 3,
 'Movie138': 13,
 'Movie139': 4,
 'Movie140': 578,
 'Movie141': 7,
 'Movie142': 1,
 'Movie143': 1,
 'Movie144': 1,
 'Movie145': 1,
 'Movie146': 1,
 'Movie147': 1,
 'Movie148': 2,
 'Movie149': 1,
 'Movie150': 3,
 'Movie151': 2,
 'Movie152': 1,
 'Movie153': 1,
 'Movie154': 1,
 'Movie155': 2,
 'Movie156': 1,
 'Movie157': 4,
 'Movie158': 66,
 'Movie159': 2,
 'Movie160': 6,
 'Movie161': 25,
 'Movie162': 15,
 'Movie163': 13,
 'Movie164': 4,
 'Movie165': 1,
 'Movie166': 2,
 'Movie167': 4,
 'Movie168': 4,
 'Movie169': 4,
 'Movie170': 3,
 'Movie171': 1,
 'Movie172': 2,
 'Movie173': 15,
 'Movie174': 4,
 'Movie175': 1,
 'Movie176': 1,
 'Movie177': 1,
 'Movie178': 1,
 'Movie179': 7,
 'Movie180': 1,
 'Movie181': 2,
 'Movie182': 30,
 'Movie183': 1,
 'Movie184': 17,
 'Movie185': 24,
 'Movie186': 9,
 'Movie187': 1,
 'Movie188': 6,
 'Movie189': 5,
 'Movie190': 7,
 'Movie191': 6,
 'Movie192': 10,
 'Movie193': 7,
 'Movie194': 7,
 'Movie195': 1,
 'Movie196': 9,
 'Movie197': 5,
 'Movie198': 2,
 'Movie199': 1,
 'Movie200': 8,
 'Movie201': 3,
 'Movie202': 6,
 'Movie203': 1,
 'Movie204': 8,
 'Movie205': 35,
 'Movie206': 13}

In [136]:
five_rating = {}
for i,j in avg_rating.items():
    if j == 5.0:
         five_rating[i] = avg_rating[i]

In [137]:
for i,j in five_rating.items():
    five_rating[i] = views_dict[i]

In [138]:
top_five_rating = {k: v for k, v in sorted(five_rating.items(), key=lambda item: item[1],reverse=True)}

In [139]:
top_5_movies = []
for i in range(5):
    top_5_movies.append(list(top_five_rating.keys())[i])

In [140]:
top_5_movies

['Movie186', 'Movie188', 'Movie191', 'Movie12', 'Movie101']

In [141]:
least_audience = {k: v for k, v in sorted(five_rating.items(), key=lambda item: item[1])}

In [142]:
least_audience_list = []
top_5_movies = []
for i in range(5):
    least_audience_list.append(list(least_audience.keys())[i])

In [143]:
least_audience_list

['Movie1', 'Movie2', 'Movie7', 'Movie8', 'Movie9']